version: "3.9"
services:
  auth:
    build:
      context: ./auth
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./auth:/work
    depends_on:
      - db
  nginx:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./auth:/work
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
    depends_on:
      - auth
  api:
    build: 
      context: ./api
      dockerfile: ./docker/Dockerfile
    working_dir: /api
    volumes:
      - /api/tmp
      - ./api:/api
    ports:
      - 8000:8000
    environment:
      DB_USER: root
      DB_PASSWORD: secret
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: laravel_local
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: laravel_local
      MYSQL_USER: phper
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: Asia/Tokyo
volumes:
  db-store:
